
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const App = lazy(() => import("./pages/App.tsx"));
const CohortDetails = lazy(() => import("./pages/CohortDetails.tsx"));
const CustomerDetails = lazy(() => import("./pages/CustomerDetails.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/cohort-details", element: <UserGuard><CohortDetails /></UserGuard>},
	{ path: "/cohortdetails", element: <UserGuard><CohortDetails /></UserGuard>},
	{ path: "/customer-details", element: <UserGuard><CustomerDetails /></UserGuard>},
	{ path: "/customerdetails", element: <UserGuard><CustomerDetails /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},

];
